spring.application.name=authservice

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
eureka.instance.prefer-ip-address=true

# JWT Configuration (Secret should be at least 256 bits)
application.security.jwt.secret=${JWT_SECRET:bXktMzItY2hhcmFjdGVyLXVsdHJhLXNlY3VyZS1hbmQtdWx0cmEtbG9uZy1zZWNyZXQ=}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
